project_id = "smart-chat"

[functions.checklist-media]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.lovable-driver-sync]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.vehicle-unlock]
verify_jwt = true

[functions.tracking-simulator]
verify_jwt = false
